### PR TITLE
fixed acuqire all command

### LINKED ISSUE #102: Fix full acquistion command :)
The full acquire sequence command needs adjusted. It may be best accomplished through multiple commands in a sequential command group that is started by the button. It should work like this:
Sushi and main acquire start
Laser in acquisition sees note and transition turns on, sushi runs backwards
Bottom storage laser sees note and storage turns on, main acquire turns off
Top storage sees note, storage and transition turn off

### PR DESCRIPTION
**Pull request by Griffin9881**
### Pull Request

---------------------------------------------

#### Issue Number

Closes #102

### CODE REVIEW

File: src/main/java/frc/robot/commands/ScoringElevatorPositionCommand.java [hunk 1]
```diff
@@ -9,6 +9,15 @@ public class ScoringElevatorPositionCommand extends Command {
     private ScoringElevator scoring = ScoringElevator.getInstance();
     private ElevatorSetpoints scoringState;
 
+    private boolean noFinish = false;
```
Comment (reediculous456) [inline src/main/java/frc/robot/commands/ScoringElevatorPositionCommand.java:12]: I think the default of this should be true so that by default this command will not end until cancelled

File: src/main/java/frc/robot/commands/FullAcquireCommand.java [hunk 2]
```diff
@@ -0,0 +1,15 @@
+package frc.robot.commands;
+
+import edu.wpi.first.wpilibj2.command.Command;
+import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
+import frc.robot.subsystems.ScoringElevator.ElevatorSetpoints;
+
+public class FullAcquireCommand extends Command {
```
Comment (reediculous456) [inline src/main/java/frc/robot/commands/FullAcquireCommand.java:7]:
```suggestion
public class FullAcquireCommand extends SequentialCommandGroup {
```

File: src/main/java/frc/robot/commands/FullAcquireCommand.java [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+    public void fullAcquireCommand() {
+        new SequentialCommandGroup(
```
Comment (reediculous456) [inline src/main/java/frc/robot/commands/FullAcquireCommand.java:9]:
```suggestion
        this.addCommands(
```

File: src/main/java/frc/robot/commands/FullAcquireCommand.java [hunk 4]
```diff
@@ -0,0 +1,15 @@
+package frc.robot.commands;
+
+import edu.wpi.first.wpilibj2.command.Command;
+import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
+import frc.robot.subsystems.ScoringElevator.ElevatorSetpoints;
+
+public class FullAcquireCommand extends Command {
+    public void fullAcquireCommand() {
```
Comment (reediculous456) [inline src/main/java/frc/robot/commands/FullAcquireCommand.java:8]:
```suggestion
    public FullAcquireCommand() {
```

**Review by reediculous456 — CHANGES_REQUESTED** [review]

**Review by reediculous456 — DISMISSED** [review]

**Review by reediculous456 — APPROVED** [review]
