### PR TITLE
Fixed return statement

### LINKED ISSUE #121: Fix lift get max lift commanc

### PR DESCRIPTION
**Pull request by Griffin9881**
### Pull Request

---------------------------------------------

#### Issue Number

Closes #121

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/Lift.java [hunk 1]
```diff
@@ -141,11 +141,12 @@ public void runRightUp() {
     }
 
     public boolean isLiftUp() {
-        return rightLiftEncoder.getPosition() < LiftConstants.maxExtension;
+        return rightLiftEncoder.getPosition() < LiftConstants.maxExtension
```
Comment (reediculous456) [inline src/main/java/frc/robot/subsystems/Lift.java:144]: So this takes into account both sides for the command, however you also changed the up functions to use this condition so if the left side is all the way up but the right side isn’t, then the left will keep going up and cause damage to the robot. 
We need 2 is up functions, one for left and one for right. You could add a 3rd to combine the two if you want or just combine both in the is finished of the command

**Review by reediculous456 — APPROVED** [review]

**Review by reediculous456 — CHANGES_REQUESTED** [review]
Build is failing

**Review by reediculous456 — APPROVED** [review]

**Review by reediculous456 — APPROVED** [review]
