### PR TITLE
135 fix pids for auton

### LINKED ISSUE #135: fix PIDs for auton

### PR DESCRIPTION
**Pull request by Griffin9881**
### Pull Request

---------------------------------------------

#### Issue Number

Closes #135

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/Dashboard.java [hunk 1]
```diff
@@ -100,6 +103,11 @@ private Dashboard() {
                 .withPosition(2, 1)
                 .withSize(4, 3)
                 .withWidget(BuiltInWidgets.kField);
+        BuiltInAccelerometer acc = new BuiltInAccelerometer();
```
Comment (reediculous456) [inline src/main/java/frc/robot/subsystems/Dashboard.java:106]: You should revert this file

**Review by reediculous456 — CHANGES_REQUESTED** [review]
